### ISSUE TITLE
Duplicates using the same word

### ISSUE THREAD

**Issue by molinto** [wooorm/retext-keywords#1]
Hi, great project btw!

Slight issue using same word in the title, eg:
"How to Get best More Likes on Your Facebook Page " ->  "keywords": [ "facebook", "page" ].

But if you put **page** in the title twice:
"How to Get best More **page** Likes on Your Facebook Page" ->  "keywords": [  "page,page" ].

```javascript

var Retext = require('retext'),
    visit = require('retext-visit'),
    keywords = require('retext-keywords'),
    sentiment = require('retext-sentiment');
var rt = new Retext().use(visit).use(keywords).use(sentiment);

rt.parse(headline, function (err, tree) {
        if (err) return cb(err);
        if (tree.length == 0) {
            return cb(new Error('Error loading the data!'));
        }

       var s = []
      _.forEach(tree.keywords({ 'minimum': 1 }), function(n) {
            s.push(n.nodes.toString());
      });
}
```

**Comment by wooorm** [comment]
You got me looking there for a while: It’s some time ago since i looked at it.
However, take another look at the results you get: `[ "facebook", "page" ]`, and `[ "page,page" ]` (note the comma/quotes).

That’s because `n.nodes` is an array of one or more nodes: in the first headline, it contains one node for each entry. In the second, two nodes for one entry.

I’m not sure what your goal is, if you want to get the stem, you should check `n.stem`, if you want to get an example word, check `n.nodes[0].toString()`, if you’d like to get all words, `n.nodes.join(', ')`, note the space, might be better :)

Did that help?

**Comment by molinto** [comment]
Thanks for getting back so quickly.  I just want the keywords from a phrase please.

I'll try:
```javascript
s.push(n.nodes[0].toString());
```
